// <auto-generated />
using HainDanielsApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HainDanielsApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201005151127_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HainDanielsApi.Models.Product", b =>
                {
                    b.Property<int>("M3Item")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BatchOrderMultiples");

                    b.Property<string>("Cap");

                    b.Property<string>("Description");

                    b.Property<string>("Domino");

                    b.Property<string>("JarCode");

                    b.Property<int>("Label");

                    b.Property<double>("NetWeight");

                    b.Property<int>("PalletQyt");

                    b.Property<int>("SalesDays");

                    b.Property<int>("UnitsPerCase");

                    b.Property<string>("VarietyCode");

                    b.Property<string>("Zambelli");

                    b.HasKey("M3Item");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
